# Generated by Django 2.1.15 on 2021-04-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'managed': False},
        ),
    ]
