# Generated by Django 2.1.15 on 2021-04-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0003_auto_20210415_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=320)),
                ('address', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
