# Generated by Django 2.1.15 on 2021-04-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
