# Generated by Django 2.1 on 2021-04-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0008_exerciseprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('TodoID', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Todo',
                'managed': False,
            },
        ),
    ]
