# Generated by Django 2.1.15 on 2021-04-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0002_auto_20210415_1517'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='Exercise',
        ),
    ]
