# Generated by Django 2.1.15 on 2021-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0007_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgram',
            fields=[
                ('ExerciseProgramID', models.IntegerField(primary_key=True, serialize=False)),
                ('Expect', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Exercise Program',
                'managed': False,
            },
        ),
    ]
