# Generated by Django 3.1.7 on 2021-04-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execise',
            name='ExeciseID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
