# Generated by Django 3.1.7 on 2021-04-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0002_auto_20210403_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execise',
            options={'managed': False},
        ),
    ]
