# Generated by Django 3.1.7 on 2021-04-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0003_auto_20210408_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execise',
            options={},
        ),
    ]
