# Generated by Django 3.1.7 on 2021-04-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymho', '0004_auto_20210408_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exerciseid', models.IntegerField(db_column='ExerciseID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('rep_recommend', models.CharField(blank=True, db_column='Rep recommend', max_length=10, null=True)),
                ('activate', models.BooleanField(blank=True, db_column='Activate', null=True)),
            ],
            options={
                'db_table': 'Exercise',
            },
        ),
        migrations.DeleteModel(
            name='Execise',
        ),
    ]
